export default function HomePage() {
  return (
    <main className="errorPage">
      <div className="errorCard">
        <h1>AnnotationNav Developer Handoff</h1>
        <p>
          Open a handoff URL generated by the AnnotationNav Figma plugin. A handoff page combines the live Figma Design embed with the exported implementation annotations.
        </p>
      </div>
    </main>
  );
}
